"""initial schema

Revision ID: cc9c88c53ef9
Revises: 
Create Date: 2026-09-28 14:04:08.700602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models


# revision identifiers, used by Alembic.
revision: str = 'cc9c88c53ef9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('received_at', app.models.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'event_id', name='uq_processed_webhook_events_provider_id')
    )
    op.create_table('raw_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('uf_hint', sa.String(length=2), nullable=True),
    sa.Column('organization_hint', sa.String(length=255), nullable=True),
    sa.Column('published_at', app.models.UTCDateTime(), nullable=True),
    sa.Column('fetched_at', app.models.UTCDateTime(), nullable=False),
    sa.Column('classified_at', app.models.UTCDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_raw_items_source_external_id')
    )
    with op.batch_alter_table('raw_items', schema=None) as batch_op:
        batch_op.create_index('ix_raw_items_classified_at', ['classified_at'], unique=False)

    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('ufs', sa.JSON(), nullable=False),
    sa.Column('areas', sa.JSON(), nullable=False),
    sa.Column('education', sa.String(length=20), nullable=True),
    sa.Column('min_salary_cents', sa.Integer(), nullable=True),
    sa.Column('plan', sa.String(length=10), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('opted_out_at', app.models.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.models.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.models.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_item_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('ufs', sa.JSON(), nullable=False),
    sa.Column('areas', sa.JSON(), nullable=False),
    sa.Column('education_levels', sa.JSON(), nullable=False),
    sa.Column('vacancies', sa.Integer(), nullable=True),
    sa.Column('max_salary_cents', sa.Integer(), nullable=True),
    sa.Column('registration_deadline', sa.Date(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('created_at', app.models.UTCDateTime(), nullable=False),
    sa.Column('matched_at', app.models.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['raw_item_id'], ['raw_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_item_id')
    )
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.create_index('ix_exams_matched_at', ['matched_at'], unique=False)

    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', app.models.UTCDateTime(), nullable=False),
    sa.Column('sent_at', app.models.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscriber_id', 'exam_id', name='uq_deliveries_subscriber_exam')
    )
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.create_index('ix_deliveries_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_index('ix_deliveries_status')

    op.drop_table('deliveries')
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index('ix_exams_matched_at')

    op.drop_table('exams')
    op.drop_table('subscribers')
    with op.batch_alter_table('raw_items', schema=None) as batch_op:
        batch_op.drop_index('ix_raw_items_classified_at')

    op.drop_table('raw_items')
    op.drop_table('processed_webhook_events')
    # ### end Alembic commands ###
